In [2]:
import numpy as np

# Creation of NumPy Arrays
# NumPy arrays can be created using various methods. Here is an example of creating 1D and 2D arrays:

# Create a 1D array
array1 = np.array([1, 2, 3, 4, 5])

# Create a 2D array
array2 = np.array([[1, 2, 3], [4, 5, 6]])

In [6]:
print(array1)

[1 2 3 4 5]


In [8]:
print(array2)

[[1 2 3]
 [4 5 6]]


In [10]:
# Create a 1D array



A1 = np.array([11, 22, 34, 12, 15])

# Select the ith element of A1
print(A1[2])  # Output: 34

# Negative indexing
print(A1[-1])  # Output: 15

34
15


In [20]:

#2D Array Indexing

#For 2D arrays, you need to specify both the row and column indices
# Create a 2D array


A2 = np.array([[0, 1, 3], [4, 6, 7]])

# Select the first row of A2
print(A2[0,:])  # Output: [0 1 3]

# Select the first element of the first row
print(A2[1, 0])  # Output: 4

[0 1 3]
4


In [22]:

# Slicing NumPy Arrays
# Slicing allows you to extract parts of the array using the start:stop:step notation.

# Create a 1D array
A = np.array([11, 12, 13, 14, 15])

# Select all elements
print(A[:])  # Output: [11 12 13 14 15]

# Select elements from index 1 to 3 (exclusive)
print(A[1:4])  # Output: [12 13 14]

# Select all elements except the last one
print(A[:-1])  # Output: [11 12 13 14]

[11 12 13 14 15]
[12 13 14]
[11 12 13 14]


In [28]:
# 2D Array Slicing
# For 2D arrays, you specify slices for both rows and columns.

# Create a 2D array
students = np.array([['Alice', 'Beth', 'Cathy', 'Dorothy'],
                     [65, 78, 90, 81],
                     [71, 82, 79, 92]])

# All rows and column 1
print(students[:, 1:2])  # Output: [['Beth'], [78], [82]]

# All rows, columns 1 and 2
print(students[:, 1:3])  # Output: [['Beth', 'Cathy'], [78, 90], [82, 79]]

# All columns, rows 0 and 1
print(students[0:2, :])  # Output: [['Alice', 'Beth', 'Cathy', 'Dorothy'], [65, 78, 90, 81]]

# The last row
print(students[-1, :])  # Output: [71 82 79 92]

[['Beth']
 ['78']
 ['82']]
[['Beth' 'Cathy']
 ['78' '90']
 ['82' '79']]
[['Alice' 'Beth' 'Cathy' 'Dorothy']
 ['65' '78' '90' '81']]
['71' '82' '79' '92']


In [34]:
# Advanced Slicing and Indexing
# Negative Slicing: You can use negative indices to start counting from the end of the array.
# is ki mujy sae smjh nhi i 
# i dont know how is it working 

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])  # Output: [5 6]

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])  # Output: [2 4]

students = np.array([['Alice', 'Beth', 'Cathy', 'Dorothy'],
                     [65, 78, 90, 81],
                     [71, 82, 79, 92]])
print(students[0, ...])  # Output: ['Alice' 'Beth' 'Cathy' 'Dorothy']


[5 6]
[2 4]
['Alice' 'Beth' 'Cathy' 'Dorothy']


In [30]:
#Inspection of a NumPy Array
#Inspecting a NumPy array involves understanding its structure, dimensions, and content. 
#Here are some key methods and attributes to inspect a NumPy array:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)  # Output: (2, 3)

(2, 3)


In [32]:
# ndim Attribute: Returns the number of dimensions in the array.
print(arr.ndim)  # Output: 2

2


In [34]:
# Size and Number of Elements
# size Attribute: Returns the total number of elements in the array.
print(arr.size)  # Output: 6


6


In [36]:
# Data Type
#dtype Attribute: Returns the data type of the elements in the array.
print(arr.dtype)  # Output: int64


int64


In [38]:
# Create a sample array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Inspect the array
print("Shape:", arr.shape)  # Output: (2, 3)
print("Dimensions:", arr.ndim)  # Output: 2
print("Size:", arr.size)  # Output: 6
print("Data Type:", arr.dtype)  # Output: int64
print("Array Content:\n", arr)
# Output:
# [[1 2 3]
#  [4 5 6]]

# Statistical summaries
print("Mean:", np.mean(arr))  # Output: 3.5
print("Median:", np.median(arr))  # Output: 3.5
print("Standard Deviation:", np.std(arr))  # Output: 1.7078251276599

# Non-zero elements
arr_nonzero = np.array([0, 1, 0, 3, 0])
print("Non-zero indices:", np.nonzero(arr_nonzero))  # Output: (array([1, 3], dtype=int64),)

# Unique elements
arr_unique = np.array([1, 2, 2, 3, 4, 4, 5])
print("Unique elements:", np.unique(arr_unique))  # Output: [1 2 3 4 5]

Shape: (2, 3)
Dimensions: 2
Size: 6
Data Type: int64
Array Content:
 [[1 2 3]
 [4 5 6]]
Mean: 3.5
Median: 3.5
Standard Deviation: 1.707825127659933
Non-zero indices: (array([1, 3]),)
Unique elements: [1 2 3 4 5]


In [40]:
# mathematical operation and function on arry

# Create the arrays
a_arr = np.array([60, 70, 80, 90])
b_arr = np.arange(4)

# Add the arrays
c_arr = a_arr + b_arr

# Print the result
print(c_arr)

[60 71 82 93]


In [42]:
# Create the arrays
a_arr = np.array([60, 70, 80, 90])
b_arr = np.arange(4)

# Add the arrays
c_arr = a_arr + b_arr

# Print the result
print(c_arr)

[60 71 82 93]


In [44]:
# Create the arrays
d_arr = np.array([60, 70, 80, 90])
e_arr = np.arange(4)

# Subtract the arrays
f_arr = d_arr - e_arr

# Print the result
print(f_arr)

[60 69 78 87]


In [46]:

# Create the arrays
a_arr = np.array([60, 70, 80, 90])
b_arr = np.arange(4)

# Add the arrays using np.add()
c_arr = np.add(a_arr, b_arr)

# Print the result
print(c_arr)

[60 71 82 93]


In [48]:
# Create the arrays
d_arr = np.array([60, 70, 80, 90])
e_arr = np.arange(4)

# Subtract the arrays using np.subtract()
f_arr = np.subtract(d_arr, e_arr)

# Print the result
print(f_arr)

[60 69 78 87]


In [50]:
a = np.array([1, 2, 3, 4])
b = np.array([2, 2, 2, 2])

# Multiplication
mul_arr = a * b  # or np.multiply(a, b)
print(mul_arr)  # Output: [2 4 6 8]

# Division
div_arr = a / b  # or np.divide(a, b)
print(div_arr)  # Output: [0.5 1. 1.5 2. ]

# Exponentiation
exp_arr = a ** b  # or np.power(a, b)
print(exp_arr)  # Output: [1 4 9 16]

# Modulus
mod_arr = a % b  # or np.mod(a, b)
print(mod_arr)  # O

[2 4 6 8]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]
[1 0 1 0]


In [52]:

# Combining and Splitting Arrays


# 1. Stacking Arrays
#You can use the np.stack(), np.vstack(), np.hstack(), and np.dstack() functions to combine arrays.
# Vertical Stacking (np.vstack()):


a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.vstack((a, b))
print(c)
# Output:
# [[1 2 3]
#  [4 5 6]]

[[1 2 3]
 [4 5 6]]


In [54]:
# Horizontal Stacking (np.hstack()):


a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.hstack((a, b))
print(c)
# Output: [1 2 3 4 

[1 2 3 4 5 6]


In [56]:
# Depth Stacking (np.dstack()):


a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.dstack((a, b))
print(c)
# Output:
# [[[1 4]
#   [2 5]
#   [3 6]]]

[[[1 4]
  [2 5]
  [3 6]]]


In [58]:
#General Stacking (np.stack()):


a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.stack((a, b), axis=0)  # Vertical stacking
print(c)
# Output:
# [[1 2 3]
#  [4 5 6]]

d = np.stack((a, b), axis=1)  # Horizontal stacking
print(d)
# Output:
# [[1 4]
#  [2 5]
#  [3 6]]

e = np.stack((a, b), axis=-1)  # Depth stacking
print(e)
# Output:
# [[[1 4]
#   [2 5]
#   [3 6]]]

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [60]:

# 2. Concatenating Arrays


#You can use the np.concatenate() function to concatenate arrays along a specified axis.


a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.concatenate((a, b))
print(c)
# Output: [1 2 3 4 5 6]

# Concatenating along axis 0 (vertical)
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.concatenate((a, b), axis=0)
print(c)
# Output:
# [[1 2]
#  [3 4]
#  [5 6]
#  [7 8]]

# Concatenating along axis 1 (horizontal)
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.concatenate((a, b), axis=1)
print(c)
# Output:
# [[1 2 5 6]
#  [3 4 7 8]]

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [68]:


# 1. Splitting Along an Axis
# You can use the np.split(), np.hsplit(), np.vsplit(), and np.dsplit() functions to split arrays.
# Splitting Along a Specified Axis (np.split()):


a = np.array([1, 2, 3, 4, 5, 6])
b = np.split(a, 3)
print(b)
# Output: [array([1, 2]), array([3, 4]), array([5, 6])]



[array([1, 2]), array([3, 4]), array([5, 6])]


In [70]:
# Horizontal Splitting (np.hsplit()):


a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.hsplit(a, 3)
print(b)
# Output: [array([[1],
#                  [4]]),
#          array([[2],
#                  [5]]),
#          array([[3],
#                  [6]])]

# Vertical Splitting (np.vsplit()):


a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.vsplit(a, 2)
print(b)
# Output: [array([[1, 2, 3]]),
#          array([[4, 5, 6]])]

# Depth Splitting (np.dsplit()):


a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
b = np.dsplit(a, 2)
print(b)
# Output: [array([[[1],
#                   [3]],
#                  [[5],
#                   [7]]]),
#          array([[[2],
#                   [4]],
#                  [[6],
#                   [8]]])]


[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]
[array([[1, 2, 3]]), array([[4, 5, 6]])]
[array([[[1],
        [3]],

       [[5],
        [7]]]), array([[[2],
        [4]],

       [[6],
        [8]]])]


In [72]:

# 2. Array Reshaping
# You can use the np.reshape() function to reshape an array without changing its data.


a = np.array([1, 2, 3, 4, 5, 6])
b = np.reshape(a, (2, 3))
print(b)
# Output:
# [[1 2 3]
#  [4 5 6]]

c = np.reshape(a, (3, 2))
print(c)
# Output:
# [[1 2]
#  [3 4]
#  [5 6]]




[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [74]:
# Combining arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Vertical stacking
c = np.vstack((a, b))
print("Vertical Stacking:\n", c)

# Horizontal stacking
d = np.hstack((a, b))
print("Horizontal Stacking:\n", d)

# Depth stacking
e = np.dstack((a, b))
print("Depth Stacking:\n", e)

# Concatenating arrays
f = np.concatenate((a, b))
print("Concatenation:\n", f)

# Splitting arrays
g = np.array([1, 2, 3, 4, 5, 6])
h = np.split(g, 3)
print("Splitting Along Axis:\n", h)

i = np.array([[1, 2, 3], [4, 5, 6]])
j = np.hsplit(i, 3)
print("Horizontal Splitting:\n", j)

k = np.array([[1, 2, 3], [4, 5, 6]])
l = np.vsplit(k, 2)
print("Vertical Splitting:\n", l)

m = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
n = np.dsplit(m, 2)
print("Depth Splitting:\n", n)

# Reshaping arrays
o = np.array([1, 2, 3, 4, 5, 6])
p = np.reshape(o, (2, 3))
print("Reshaping to (2, 3):\n", p)

q = np.reshape(o, (3, 2))
print("Reshaping to (3, 2):\n", q)

Vertical Stacking:
 [[1 2 3]
 [4 5 6]]
Horizontal Stacking:
 [1 2 3 4 5 6]
Depth Stacking:
 [[[1 4]
  [2 5]
  [3 6]]]
Concatenation:
 [1 2 3 4 5 6]
Splitting Along Axis:
 [array([1, 2]), array([3, 4]), array([5, 6])]
Horizontal Splitting:
 [array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]
Vertical Splitting:
 [array([[1, 2, 3]]), array([[4, 5, 6]])]
Depth Splitting:
 [array([[[1],
        [3]],

       [[5],
        [7]]]), array([[[2],
        [4]],

       [[6],
        [8]]])]
Reshaping to (2, 3):
 [[1 2 3]
 [4 5 6]]
Reshaping to (3, 2):
 [[1 2]
 [3 4]
 [5 6]]


In [78]:
# Adding and Removing Elements in the Arrays

# 1. Appending Elements
# You can use the np.append() function to add elements to an array.


a = np.array([1, 2, 3])
b = np.append(a, 4)
print(b)  # Output: [1 2 3 4]

# Appending multiple elements
c = np.append(a, [4, 5, 6])
print(c)  # Output: [1 2 3 4 5 6]

# 2. Inserting Elements
# You can use the np.insert() function to insert elements at a specified position.


a = np.array([1, 2, 3])
b = np.insert(a, 1, 4)
print(b)  # Output: [1 4 2 3]

# Inserting multiple elements
c = np.insert(a, 1, [4, 5])
print(c)  # Output: [1 4 5 2 3]

# 3. Concatenating Arrays
# You can use the np.concatenate() function to concatenate arrays.


a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.concatenate((a, b))
print(c)  # Output: [1 2 3 4 5 6]


[1 2 3 4]
[1 2 3 4 5 6]
[1 4 2 3]
[1 4 5 2 3]
[1 2 3 4 5 6]


In [80]:

# Removing Elements

# 1. Deleting Elements
# You can use the np.delete() function to delete elements from an array.


a = np.array([1, 2, 3, 4, 5])
b = np.delete(a, 2)
print(b)  # Output: [1 2 4 5]

# Deleting multiple elements
c = np.delete(a, [1, 3])
print(c)  # Output: [1 3 5]

# 2. Slicing to Remove Elements
# You can use slicing to create a new array without certain elements.


a = np.array([1, 2, 3, 4, 5])
b = np.concatenate((a[:2], a[3:]))
print(b)  # Output: [1 2 4 5]




[1 2 4 5]
[1 3 5]
[1 2 4 5]


In [82]:

# Adding elements
a = np.array([1, 2, 3])
b = np.append(a, 4)
print("Appending 4 to a:\n", b)

c = np.append(a, [4, 5, 6])
print("Appending [4, 5, 6] to a:\n", c)

d = np.insert(a, 1, 4)
print("Inserting 4 at position 1 in a:\n", d)

e = np.insert(a, 1, [4, 5])
print("Inserting [4, 5] at position 1 in a:\n", e)

f = np.concatenate((a, [4, 5, 6]))
print("Concatenating [4, 5, 6] to a:\n", f)

# Removing elements
g = np.delete(a, 1)
print("Deleting element at position 1 from a:\n", g)

h = np.delete(a, [1, 2])
print("Deleting elements at positions 1 and 2 from a:\n", h)

i = np.concatenate((a[:1], a[2:]))
print("Removing element at position 1 from a using slicing:\n", i)

# Summary of operations
print("Original array a:\n", a)
print("Array after appending 4:\n", b)
print("Array after inserting 4 at position 1:\n", d)
print("Array after deleting element at position 1:\n", g)

Appending 4 to a:
 [1 2 3 4]
Appending [4, 5, 6] to a:
 [1 2 3 4 5 6]
Inserting 4 at position 1 in a:
 [1 4 2 3]
Inserting [4, 5] at position 1 in a:
 [1 4 5 2 3]
Concatenating [4, 5, 6] to a:
 [1 2 3 4 5 6]
Deleting element at position 1 from a:
 [1 3]
Deleting elements at positions 1 and 2 from a:
 [1]
Removing element at position 1 from a using slicing:
 [1 3]
Original array a:
 [1 2 3]
Array after appending 4:
 [1 2 3 4]
Array after inserting 4 at position 1:
 [1 4 2 3]
Array after deleting element at position 1:
 [1 3]


In [84]:
# Search, Sort, and Filter Arrays

# Searching Arrays

# 1. Finding Indices of Elements
# You can use the np.where() function to find the indices of elements that satisfy a condition.


a = np.array([1, 2, 3, 4, 5])
indices = np.where(a > 3)
print(indices)  # Output: (array([3, 4], dtype=int64),)

# 2. Finding Specific Values
# You can use the np.where() function or simple indexing to find specific values.


a = np.array([1, 2, 3, 4, 5])
indices = np.where(a == 3)
print(a[indices])  # Output: [3]


(array([3, 4]),)
[3]


In [86]:

# Sorting Arrays

# 1. Sorting Arrays
# You can use the np.sort() function to sort arrays.

a = np.array([3, 1, 4, 2, 5])
sorted_a = np.sort(a)
print(sorted_a)  # Output: [1 2 3 4 5]

# 2. Sorting Along a Specific Axis
# For multi-dimensional arrays, you can specify the axis along which to sort.


a = np.array([[3, 1, 4], [2, 5, 6]])
sorted_a = np.sort(a, axis=1)
print(sorted_a)
# Output:
# [[1 3 4]
#  [2 5 6]]


[1 2 3 4 5]
[[1 3 4]
 [2 5 6]]


In [88]:

# Filtering Arrays

# 1. Boolean Indexing
# You can use boolean indexing to filter arrays based on conditions.


a = np.array([1, 2, 3, 4, 5])
filtered_a = a[a > 3]
print(filtered_a)  # Output: [4 5]

# 2. Using np.where() for Filtering
# You can use np.where() to filter arrays based on conditions.

a = np.array([1, 2, 3, 4, 5])
filtered_a = np.where(a > 3, a, 0)
print(filtered_a)  # Output: [0 0 0 4 5]




[4 5]
[0 0 0 4 5]


In [90]:
# Searching arrays
a = np.array([1, 2, 3, 4, 5])
indices = np.where(a > 3)
print("Indices of elements greater than 3:", indices)

# Finding specific values
specific_value = a[np.where(a == 3)]
print("Value 3 in array:", specific_value)

# Sorting arrays
sorted_a = np.sort(a)
print("Sorted array:", sorted_a)

# Sorting along a specific axis
b = np.array([[3, 1, 4], [2, 5, 6]])
sorted_b = np.sort(b, axis=1)
print("Sorted array along axis 1:\n", sorted_b)

# Filtering arrays using boolean indexing
filtered_a = a[a > 3]
print("Filtered array with values greater than 3:", filtered_a)

# Filtering arrays using np.where()
filtered_b = np.where(a > 3, a, 0)
print("Filtered array with values greater than 3 using np.where():", filtered_b)

# Additional Methods
# np.argmax() and np.argmin(): Find the indices of the maximum and minimum values.

a = np.array([1, 2, 3, 4, 5])
max_index = np.argmax(a)
min_index = np.argmin(a)
print("Index of maximum value:", max_index)
print("Index of minimum value:", min_index)

# np.searchsorted(): Find the indices where elements should be inserted to maintain sorted order.

a = np.array([1, 3, 5, 7])
indices = np.searchsorted(a, [2, 4, 6])
print("Indices for inserting [2, 4, 6]:", indices)

Indices of elements greater than 3: (array([3, 4]),)
Value 3 in array: [3]
Sorted array: [1 2 3 4 5]
Sorted array along axis 1:
 [[1 3 4]
 [2 5 6]]
Filtered array with values greater than 3: [4 5]
Filtered array with values greater than 3 using np.where(): [0 0 0 4 5]
Index of maximum value: 4
Index of minimum value: 0
Indices for inserting [2, 4, 6]: [1 2 3]


In [ ]:
#  Aggregating Functions in Arrays

# Available Aggregate Functions
# NumPy provides several aggregate functions to work with arrays, including:
# Sum: np.sum - Calculates the sum of array elements.

arr = np.array([1, 2, 3, 4, 5])
print(np.sum(arr))  # Output: 15

# Mean: np.mean - Computes the arithmetic mean or average.

arr = np.array([1, 2, 3, 4, 5])
print(np.mean(arr))  # Output: 3.0

# Median: np.median - Finds the median or middle value of the data.

arr = np.array([1, 2, 3, 4, 5])
print(np.median(arr))  # Output: 3.0

# Minimum and Maximum: np.min and np.max - Get the minimum and maximum elements of the array.

arr = np.array([1, 2, 3, 4, 5])
print(np.min(arr))  # Output: 1
print(np.max(arr))  # Output: 5

# Standard Deviation and Variance: np.std and np.var - Calculate the standard deviation and variance.

arr = np.array([1, 2, 3, 4, 5])
print(np.std(arr))  # Output: 1.4142135623730951
print(np.var(arr))  # Output: 2.0

# Product: np.prod - Computes the product of array elements.

arr = np.array([1, 2, 3, 4, 5])
print(np.prod(arr))  # Output: 120

Cumulative Sum and Product: np.cumsum and np.cumprod - Compute the cumulative sum and product.
python
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(np.cumsum(arr))  # Output: [1 3 6 10 15]
print(np.cumprod(arr))  # Output: [ 1  2  6 24 120]

Aggregation Along Axes
For multi-dimensional arrays, you can specify the axis along which to perform the aggregation using the axis parameter:
Sum along a specific axis:
python
import numpy as np
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(np.sum(arr2d, axis=0))  # Output: [5 7 9]
print(np.sum(arr2d, axis=1))  # Output: [6 15]

Mean along a specific axis:
python
import numpy as np
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(np.mean(arr2d, axis=0))  # Output: [2.5 3.5 4.5]
print(np.mean(arr2d, axis=1))  # Output: [2. 5.]

Handling NaN Values
NumPy also provides NaN-safe versions of these aggregate functions, which ignore missing values marked by NaN:
Example:
python
import numpy as np
arr = np.array([1, 2, np.nan, 4, 5])
print(np.nansum(arr))  # Output: 12.0
print(np.nanmean(arr))  # Output: 3.0